# Generated by Django 3.2.3 on 2021-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
