# Generated by Django 3.2.3 on 2021-06-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20210603_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headQuarters', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('branch_Address', models.TextField(max_length=50)),
                ('employee_ID', models.IntegerField(null=True)),
                ('employee_Name', models.CharField(max_length=20, null=True)),
                ('performance', models.CharField(max_length=40, null=True)),
            ],
            options={
                'ordering': ['branch'],
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.organisation'),
        ),
    ]
